project:
  type: book

execute:
  eval: false
  warning: false
  message: false

book:
  title: "R for Clinical Data Science"
  author: "Thibault Dupont"
  date: today
  chapters:
    - index.qmd
    - 01-r-basics.qmd
    - 02-rmarkdown.qmd
    - 03-data-import.qmd
    - 04-dplyr-wrangling.qmd
    - 05-efficient-programming.qmd
    - 06-ggplot2.qmd
    - 07-gtsummary.qmd
    - 08-regression-glm.qmd
    - 09-survival-analysis.qmd
    - 10-contingency-tables.qmd
    - 11-bayesian-intro.qmd
    - 12-factor-analysis.qmd
    - 13-machine-learning.qmd
    - 14-shiny.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: false
    toc: true
    toc-depth: 3
    number-sections: true
    highlight-style: github
    df-print: paged
